---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-internal-service
  labels:
    app: events-internal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-internal-service
  template:
    metadata:
      labels:
        app: events-internal-service
    spec:
      containers:
      - name: avenger-backend
        image: gcr.io/playground-s-11-0bd726/internal-image:v1.0.0
        env:
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8082
          name: "events-port"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: events-internal-service
spec: 
  ports: 
     -  port: 80
        protocol: TCP
        targetPort: 8082
  selector: 
    app: events-internal-service
  type: ClusterIP
